### ISSUE TITLE
Library has a bug for negative numbers

### ISSUE THREAD

**Issue by salvadorfto** [johnrbnsn/Adafruit_Python_MAX31856#1]
Hi, I was trying out the library with a thermocouple certified by NIST and as I went below 0°C the temperature instantly jumped to -2000°C

**Comment by johnrbnsn** [comment]
I think the latest commit should fix the problem, could you test it for me and let me know?  I don't have access to negative temperatures :)

**Comment by salvadorfto** [comment]
Of course, I've access to negatives down to -80. Check email please

**Comment by johnrbnsn** [comment]
Commit https://github.com/johnrbnsn/Adafruit_Python_MAX31856/commit/df381b0b750ae43166066aab7eb2c3686b08deb8 fixes bug.  Physically confirmed by https://github.com/salvadorfto on lab equipment.

Issue closed, thanks for your help!

JR
