### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'cs'

### ISSUE THREAD

**Issue by py2pi** [johnrbnsn/Adafruit_Python_MAX31856#11]
when I'm trying with this package it's giving me error like this:
Traceback (most recent call last):
  File "t.py", line 11, in <module>
    sensor = MAX31856(clk=CLK, cs=CS, do=DO, di=DI)
TypeError: __init__() got an unexpected keyword argument 'cs'
when I'm trying with MAX31856 package it's giving me result, but only 0*C or 32*F
Please help me I got stuck on this from few days back. And I've to submit project.

**Comment by johnrbnsn** [comment]
I know this is really old, but please see the example below. MAX31856 expects the SPI config to be in a dictionary, not as individual arguments. Same example as in the [simpletest.py](https://github.com/johnrbnsn/Adafruit_Python_MAX31856/blob/master/Adafruit_MAX31856/max31856.py) examples.

    software_spi = {"clk": 25, "cs": 8, "do": 9, "di": 10}
    sensor = MAX31856(software_spi=software_spi)
