### ISSUE TITLE
python3 support? 

### ISSUE THREAD

**Issue by seanroark** [johnrbnsn/Adafruit_Python_MAX31856#3]
Followed the install instructions and I can import the library using python2 but not using python3. It is installed in python3.4/dist-packages/Adafruit_MAX31856.

Is the apt-get need something different for python3?

This is on a rasberry pi running latest Raspbian. 

![max31856_import_err](https://cloud.githubusercontent.com/assets/5447312/22038592/d60bc8a8-dcc9-11e6-90a5-2bdf8328bbfe.png)

**Comment by johnrbnsn** [comment]
Did you install it with Python3 too?  If your pip is setup for Python2, then the module probably didn't install for Python3.  You can try to pip install using a 'venv' setup with Python3.  

Alternatively, copy the 'simpletest.py' into the same directory as 'Adafruit_Python_MAX31856' directory which contains 'max31856.py' and try running it directly.  

LMK, thanks.
JR

**Comment by seanroark** [comment]
Its definitely pip installed in python 2 and 3. We are trying to get away from python 2 but a few things are keeping it around so we are well versed in the whole 2to3 thing.

**Comment by johnrbnsn** [comment]
Took me a while to get back to this, I've updated the README to include new instructions which I've got working with Python3.  LKM what you think.  Still no GPIO support though, any progress on your end?  I'm closing the issue since I got it working in Py3.
