### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by anand2623** [johnrbnsn/Adafruit_Python_MAX31856#6]
python3 -m venv env_py3 
this does not execute and gives the following  error 

"Command '['/home/pi/Adafruit_Python_MAX31856/env_py3/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1"

Im not able to figure out what is the issue. Please help.
BTW, I am using Raspberrypi zero w

**Comment by johnrbnsn** [comment]
What version of Python3 are you using?  Type python3 from the command line and paste the header lines, should look something like:

    john_rbnsn@instance:~$ python3
    Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
    [GCC 5.4.0 20160609] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> 

From the error it looks like you don't have venv installed, I don't think it came standard on older versions of Python3.

**Comment by anand2623** [comment]
I have version 3.4.2 of python. I am pretty new to python and raspberry pi. 
sorry for asking such trivial stuff.
I have got it working for me now.  Thanks Jhon

**Comment by johnrbnsn** [comment]
No Worries @anand2623 ! I appreciate you using the library, and the questions that go along with it. Were you able to get the negative temperature to work out too?

**Comment by anand2623** [comment]
I work on high temperature ranges anything below 75 F is not necessary for me xD. But ill give the corresponding voltages and see if it works

**Comment by anand2623** [comment]
Hey Jhon, I feel there is some issue with the write to CR1 register. Particularly this statement
self.CR1 = ((self.avgsel << 1) + self.tc_type)
It works for avgsel =0x0 (well adding zeroes), but for other options it fails. 

I feel it should be self.avgsel<<2. 
ex: avgsel =0x1 and tc_type = 0x6 => CR1 is 0 001 0110
with existing code CR1 =  0xE (according to the log)
decimal = 0000 1110

but with self.avgsel<<2 CR1 = 0x16 
decimal = 0001 0110
which sounds right as the avgsel is 6:4 and tc type is 3:0

Please let me know if I am thinking correctly about it.

**Comment by johnrbnsn** [comment]
I opened a new issue and will respond here: https://github.com/johnrbnsn/Adafruit_Python_MAX31856/issues/7

Try to open new issues for separate problems, it helps with tracking.  Thanks!
